version: '3'

networks:
   nginx-php-mysql-node:

services:
   
   # nginx
   nginx-service:
      image: nginx:stable-alpine
      container_name: nginx-container
      ports:
         - "8080:80"
      volumes:
         - ./dragAndDropBackend:/var/www/project
         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - php-service
         - mysql-service
      networks:
         - nginx-php-mysql-node

   # php
   php-service:
      build:
         context: .
         dockerfile: ./php/Dockerfile
      container_name: php_container
      ports:
         -  "9000:9000"
      volumes:
         -  ./dragAndDropBackend:/var/www/project
      networks:
         - nginx-php-mysql-node

   # mysql
   mysql-service:
      image: mysql:8
      container_name: mysql-container
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
         - "3306:3306"
      volumes:
         - "./mysql:/var/lib/mysql"
      networks:
         - nginx-php-mysql-node
      environment:
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_USER: test

   # node
   node-service:
      build:
         context: ./dragAndDropUI # Specify the context directory containing your Vite project
         dockerfile: ../node/Dockerfile  # Use your existing Dockerfile for the Node.js service
      container_name: node_container
      volumes:
         - ./dragAndDropUI/src:/app/src
         - ./dragAndDropUI/public:/app/public
      ports:
         - "3000:3000"
      networks:
         - nginx-php-mysql-node
